export const ROUTE_CHANGE_REQUESTED = 'router/ROUTE_CHANGE_REQUESTED';
export const ROUTE_CHANGE_SUCCEED = 'router/ROUTE_CHANGE_SUCCEED';
export const ROUTE_CHANGE_FAILED = 'router/ROUTE_CHANGE_FAILED';
